/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : mysql.g
 *     -                            On : 2010-11-16 16:36:05
 *     -                 for the lexer : mysqlLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer mysqlLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pmysqlLexer, which is returned from a call to mysqlLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pmysqlLexer are  as follows:
 *
 *  -  void      pmysqlLexer->T__548(pmysqlLexer)
 *  -  void      pmysqlLexer->T__549(pmysqlLexer)
 *  -  void      pmysqlLexer->T__550(pmysqlLexer)
 *  -  void      pmysqlLexer->T__551(pmysqlLexer)
 *  -  void      pmysqlLexer->T__552(pmysqlLexer)
 *  -  void      pmysqlLexer->T__553(pmysqlLexer)
 *  -  void      pmysqlLexer->T__554(pmysqlLexer)
 *  -  void      pmysqlLexer->T__555(pmysqlLexer)
 *  -  void      pmysqlLexer->T__556(pmysqlLexer)
 *  -  void      pmysqlLexer->T__557(pmysqlLexer)
 *  -  void      pmysqlLexer->T__558(pmysqlLexer)
 *  -  void      pmysqlLexer->T__559(pmysqlLexer)
 *  -  void      pmysqlLexer->T__560(pmysqlLexer)
 *  -  void      pmysqlLexer->T__561(pmysqlLexer)
 *  -  void      pmysqlLexer->T__562(pmysqlLexer)
 *  -  void      pmysqlLexer->T__563(pmysqlLexer)
 *  -  void      pmysqlLexer->T__564(pmysqlLexer)
 *  -  void      pmysqlLexer->T__565(pmysqlLexer)
 *  -  void      pmysqlLexer->T__566(pmysqlLexer)
 *  -  void      pmysqlLexer->T__567(pmysqlLexer)
 *  -  void      pmysqlLexer->T__568(pmysqlLexer)
 *  -  void      pmysqlLexer->T__569(pmysqlLexer)
 *  -  void      pmysqlLexer->T__570(pmysqlLexer)
 *  -  void      pmysqlLexer->T__571(pmysqlLexer)
 *  -  void      pmysqlLexer->T__572(pmysqlLexer)
 *  -  void      pmysqlLexer->T__573(pmysqlLexer)
 *  -  void      pmysqlLexer->T__574(pmysqlLexer)
 *  -  void      pmysqlLexer->T__575(pmysqlLexer)
 *  -  void      pmysqlLexer->T__576(pmysqlLexer)
 *  -  void      pmysqlLexer->T__577(pmysqlLexer)
 *  -  void      pmysqlLexer->T__578(pmysqlLexer)
 *  -  void      pmysqlLexer->T__579(pmysqlLexer)
 *  -  void      pmysqlLexer->T__580(pmysqlLexer)
 *  -  void      pmysqlLexer->T__581(pmysqlLexer)
 *  -  void      pmysqlLexer->T__582(pmysqlLexer)
 *  -  void      pmysqlLexer->T__583(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ACCESS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ADD(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ALL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ALTER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AND(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ANY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ARRAYLEN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ASC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AUDIT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BETWEEN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CASE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CHAR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CHECK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CLUSTER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COLUMN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COMMENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COMPRESS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONNECT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CREATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CURRENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DATETIME(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DECIMAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DEFAULT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DELETE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DESC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DISTINCT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DISTINCTROW(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DROP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ELSE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXCLUSIVE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXISTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FALSE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FLOAT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FOR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FROM(pmysqlLexer)
 *  -  void      pmysqlLexer->K_GRANT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_GROUP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_HAVING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_IDENTIFIED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_IMMEDIATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_IN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INCREMENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INDEX(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INITIAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INSERT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INTEGER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INTERSECT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INTO(pmysqlLexer)
 *  -  void      pmysqlLexer->K_IF(pmysqlLexer)
 *  -  void      pmysqlLexer->K_IS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LEVEL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LIKE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LIKE2(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LIKE4(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LIKEC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LOCK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LONG(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXEXTENTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MINUS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MODE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MODIFY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOAUDIT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOCOMPRESS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOTFOUND(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOWAIT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NULL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NUMBER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OF(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OFFLINE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ON(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ONLINE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OPTION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ORDER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PCTFREE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PRIOR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PRIVILEGES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PUBLIC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RAW(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RENAME(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RESOURCE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REVOKE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROW(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROWID(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROWLABEL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROWNUM(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROWS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SELECT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SESSION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SET(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SHARE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SIZE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SMALLINT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQLBUF(pmysqlLexer)
 *  -  void      pmysqlLexer->K_START(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SUCCESSFUL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SYNONYM(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SYSDATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TABLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_THEN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TO(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TINYINT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MEDIUMINT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TRIGGER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TRUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UID(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNIQUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UPDATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_USER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VALIDATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VALUES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VARCHAR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VARCHAR2(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VIEW(pmysqlLexer)
 *  -  void      pmysqlLexer->K_WHENEVER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_WHERE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_WITH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TEXT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TINYTEXT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MEDIUMTEXT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LONGTEXT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ENUM(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SHOW(pmysqlLexer)
 *  -  void      pmysqlLexer->K_A(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ADMIN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AFTER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ALLOCATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ANALYZE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ARCHIVE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ARCHIVELOG(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AUTHORIZATION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AUTO_INCREMENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AVG(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BACKUP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BECOME(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BEFORE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BEGIN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BIGINT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BLOCK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BODY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CACHE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CANCEL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CASCADE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CHANGE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CHARACTER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CHARSET(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CHECKPOINT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CLOSE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COBOL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COLLATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COMMIT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COMPILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONSTRAINT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONSTRAINTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONTENTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONTINUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONTROLFILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COLUMN_FORMAT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COUNT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CURSOR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CYCLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DATABASE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DATAFILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DAY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DBA(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DBTIMEZONE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DEC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DECLARE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DISABLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DISMOUNT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DOUBLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DUMP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DYNAMIC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EACH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ENABLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_END(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ENGINE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ESCAPE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EVENTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXCEPT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXCEPTIONS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXEC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXECUTE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXPLAIN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXTENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXTERNALLY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FETCH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FIXED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FLUSH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FORCE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FOREIGN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FORTRAN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FOUND(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FREELIST(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FREELISTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FUNCTION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_GO(pmysqlLexer)
 *  -  void      pmysqlLexer->K_GOTO(pmysqlLexer)
 *  -  void      pmysqlLexer->K_GROUPS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INCLUDING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INDICATOR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INITRANS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INSTANCE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_KEY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LANGUAGE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LAYER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LINK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LISTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LOGFILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LOCAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LOCKED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MANAGE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MANUAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAX(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXDATAFILES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXINSTANCES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXLOGFILES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXLOGHISTORY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXLOGMEMBERS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXTRANS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAXVALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MIN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MINEXTENTS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MINVALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MODULE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MONTH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MOUNT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NEW(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NEXT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOARCHIVELOG(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOCACHE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOCYCLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOMAXVALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOMINVALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NONE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOORDER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NORESETLOGS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NORMAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NOSORT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NUMERIC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OFF(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OLD(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ONLY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OPEN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OPTIMAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OWN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PACKAGE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PARALLEL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PCTINCREASE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PCTUSED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PLAN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PLI(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PRECISION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PRIMARY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PRIVATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PROCEDURE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PROFILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_QUOTA(pmysqlLexer)
 *  -  void      pmysqlLexer->K_READ(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RECOVER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REFERENCES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REFERENCING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RESETLOGS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RESTRICT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RESTRICTED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REUSE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROLES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROLLBACK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SAVEPOINT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SCHEMA(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SCN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SECOND(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SECTION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SEGMENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SEQUENCE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SESSIONTIMEZONE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SHARED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SNAPSHOT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SKIP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SOME(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SORT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQLCODE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQLERROR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQLSTATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STATEMENT_ID(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STATISTICS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STOP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STORAGE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SUM(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SWITCH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SYSTEM(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TABLES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TABLESPACE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TEMPORARY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_THREAD(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TIME(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TRACING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TRANSACTION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TRIGGERS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TRUNCATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNDER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNLIMITED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNTIL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_USE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_USING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_WAIT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_WHEN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_WORK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_WRITE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_YEAR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ZONE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_AUTOMATIC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BFILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BINARY_DOUBLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BINARY_FLOAT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BINARY_INTEGER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BLOB(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LONGBLOB(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MEDIUMBLOB(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TINYBLOB(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BOOLEAN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BYTE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CAST(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CLOB(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CLUSTER_SET(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COLUMN_VALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONNECT_BY_ISCYCLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONNECT_BY_ISLEAF(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CONNECT_BY_ROOT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CORR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COVAR_POP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_COVAR_SAMP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CROSS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CUBE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CUME_DIST(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DECREMENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DENSE_RANK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DIMENSION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EMPTY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EQUALS_PATH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FIRST_VALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FULL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_GROUPING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_IGNORE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INFINITE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INNER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INTERVAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ITERATE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_JOIN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_KEEP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LAG(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LAST(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LAST_VALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LEAD(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LEFT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MAIN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MEASURES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MEMBER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MLSLABEL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MODEL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MULTISET(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NAN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NATIONAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NATURAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NAV(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NCHAR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NCLOB(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NTILE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NULLS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NVARCHAR(pmysqlLexer)
 *  -  void      pmysqlLexer->K_NVARCHAR2(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OBJECT_ID(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OBJECT_VALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ORA_ROWSCN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OUTER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OVER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PARTITION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PERCENTILE_CONT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PERCENTILE_DISC(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PERCENT_RANK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PIVOT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PLS_INTEGER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_POSITIVE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PRESENT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RANK(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RATIO_TO_REPORT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REFERENCE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGEXP_LIKE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_AVGX(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_AVGY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_COUNT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_INTERCEPT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_R2(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_SLOPE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_SXX(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_SXY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REGR_SYY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RIGHT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROLLUP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ROW_NUMBER(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RULES(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SAMPLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SEARCH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SEQUENTIAL(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SETS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SINGLE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STDDEV(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STDDEV_POP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STDDEV_SAMP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SUBMULTISET(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SUBPARTITION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_THE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TIMESTAMP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_TYPE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNBOUNDED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNDER_PATH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UPDATED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UPSERT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UROWID(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VARIANCE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VARYING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VAR_POP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VAR_SAMP(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VERSIONS_ENDSCN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VERSIONS_ENDTIME(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VERSIONS_OPERATION(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VERSIONS_STARSCN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VERSIONS_STARTTIME(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VERSIONS_XID(pmysqlLexer)
 *  -  void      pmysqlLexer->K_XML(pmysqlLexer)
 *  -  void      pmysqlLexer->K_XMLDATA(pmysqlLexer)
 *  -  void      pmysqlLexer->K_ERRORS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FIRST(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LIMIT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_OFFSET(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LOG(pmysqlLexer)
 *  -  void      pmysqlLexer->K_REJECT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RETURN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RETURNING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MERGE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MATCHED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FOLLOWING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RANGE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SIBLINGS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNPIVOT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_UNSIGNED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_BREADTH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_DEPTH(pmysqlLexer)
 *  -  void      pmysqlLexer->K_EXCLUDE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INCLUDE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MIVALUE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_PRECEDING(pmysqlLexer)
 *  -  void      pmysqlLexer->K_RESPECT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SEED(pmysqlLexer)
 *  -  void      pmysqlLexer->K_VERSIONS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_HIGH_PRIORITY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_STRAIGHT_JOIN(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQL_SMALL_RESULT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQL_BIG_RESULT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQL_BUFFER_RESULT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQL_CACHE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQL_NO_CACHE(pmysqlLexer)
 *  -  void      pmysqlLexer->K_SQL_CALC_FOUND_ROWS(pmysqlLexer)
 *  -  void      pmysqlLexer->K_INNODB(pmysqlLexer)
 *  -  void      pmysqlLexer->K_MYISAM(pmysqlLexer)
 *  -  void      pmysqlLexer->K_LOW_PRIORITY(pmysqlLexer)
 *  -  void      pmysqlLexer->K_FULLTEXT(pmysqlLexer)
 *  -  void      pmysqlLexer->K_CURRENT_TIMESTAMP(pmysqlLexer)
 *  -  void      pmysqlLexer->STUPID_MYSQL_DATE(pmysqlLexer)
 *  -  void      pmysqlLexer->STUPID_MYSQL_TIMESTAMP(pmysqlLexer)
 *  -  void      pmysqlLexer->QUOTED_STRING(pmysqlLexer)
 *  -  void      pmysqlLexer->QSTRING(pmysqlLexer)
 *  -  void      pmysqlLexer->QS_ANGLE(pmysqlLexer)
 *  -  void      pmysqlLexer->QS_BRACE(pmysqlLexer)
 *  -  void      pmysqlLexer->QS_BRACK(pmysqlLexer)
 *  -  void      pmysqlLexer->QS_PAREN(pmysqlLexer)
 *  -  void      pmysqlLexer->QS_OTHER_CH(pmysqlLexer)
 *  -  void      pmysqlLexer->QS_OTHER(pmysqlLexer)
 *  -  void      pmysqlLexer->ID(pmysqlLexer)
 *  -  void      pmysqlLexer->SEMI(pmysqlLexer)
 *  -  void      pmysqlLexer->COLON(pmysqlLexer)
 *  -  void      pmysqlLexer->DOUBLEDOT(pmysqlLexer)
 *  -  void      pmysqlLexer->DOT(pmysqlLexer)
 *  -  void      pmysqlLexer->POINT(pmysqlLexer)
 *  -  void      pmysqlLexer->COMMA(pmysqlLexer)
 *  -  void      pmysqlLexer->EXPONENT(pmysqlLexer)
 *  -  void      pmysqlLexer->ASTERISK(pmysqlLexer)
 *  -  void      pmysqlLexer->AT_SIGN(pmysqlLexer)
 *  -  void      pmysqlLexer->RPAREN(pmysqlLexer)
 *  -  void      pmysqlLexer->LPAREN(pmysqlLexer)
 *  -  void      pmysqlLexer->RBRACK(pmysqlLexer)
 *  -  void      pmysqlLexer->LBRACK(pmysqlLexer)
 *  -  void      pmysqlLexer->PLUS(pmysqlLexer)
 *  -  void      pmysqlLexer->MINUS(pmysqlLexer)
 *  -  void      pmysqlLexer->DIVIDE(pmysqlLexer)
 *  -  void      pmysqlLexer->EQ(pmysqlLexer)
 *  -  void      pmysqlLexer->PERCENTAGE(pmysqlLexer)
 *  -  void      pmysqlLexer->LLABEL(pmysqlLexer)
 *  -  void      pmysqlLexer->RLABEL(pmysqlLexer)
 *  -  void      pmysqlLexer->ASSIGN(pmysqlLexer)
 *  -  void      pmysqlLexer->ARROW(pmysqlLexer)
 *  -  void      pmysqlLexer->VERTBAR(pmysqlLexer)
 *  -  void      pmysqlLexer->DOUBLEVERTBAR(pmysqlLexer)
 *  -  void      pmysqlLexer->NOT_EQ(pmysqlLexer)
 *  -  void      pmysqlLexer->LTH(pmysqlLexer)
 *  -  void      pmysqlLexer->LEQ(pmysqlLexer)
 *  -  void      pmysqlLexer->GTH(pmysqlLexer)
 *  -  void      pmysqlLexer->GEQ(pmysqlLexer)
 *  -  void      pmysqlLexer->NUMBER(pmysqlLexer)
 *  -  void      pmysqlLexer->NUM(pmysqlLexer)
 *  -  void      pmysqlLexer->QUOTE(pmysqlLexer)
 *  -  void      pmysqlLexer->BACKTICK(pmysqlLexer)
 *  -  void      pmysqlLexer->DOUBLEQUOTED_STRING(pmysqlLexer)
 *  -  void      pmysqlLexer->BACKQUOTED_STRING(pmysqlLexer)
 *  -  void      pmysqlLexer->WS(pmysqlLexer)
 *  -  void      pmysqlLexer->SL_COMMENT(pmysqlLexer)
 *  -  void      pmysqlLexer->ML_COMMENT(pmysqlLexer)
 *  -  void      pmysqlLexer->Tokens(pmysqlLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_mysqlLexer_H
#define _mysqlLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct mysqlLexer_Ctx_struct mysqlLexer, * pmysqlLexer;



#include "pgify.h"
#include <glib.h>


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

/** Context tracking structure for mysqlLexer
 */
struct mysqlLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT__548)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__549)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__550)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__551)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__552)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__553)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__554)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__555)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__556)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__557)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__558)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__559)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__560)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__561)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__562)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__563)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__564)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__565)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__566)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__567)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__568)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__569)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__570)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__571)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__572)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__573)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__574)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__575)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__576)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__577)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__578)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__579)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__580)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__581)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__582)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mT__583)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ACCESS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ADD)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ALL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ALTER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AND)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ANY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ARRAYLEN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ASC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AUDIT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BETWEEN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CASE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CHAR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CHECK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CLUSTER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COLUMN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COMMENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COMPRESS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONNECT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CREATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CURRENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DATETIME)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DECIMAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DEFAULT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DELETE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DESC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DISTINCT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DISTINCTROW)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DROP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ELSE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXCLUSIVE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXISTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FALSE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FLOAT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FOR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FROM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_GRANT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_GROUP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_HAVING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_IDENTIFIED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_IMMEDIATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_IN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INCREMENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INDEX)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INITIAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INSERT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INTEGER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INTERSECT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INTO)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_IF)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_IS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LEVEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LIKE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LIKE2)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LIKE4)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LIKEC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LOCK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LONG)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXEXTENTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MINUS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MODE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MODIFY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOAUDIT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOCOMPRESS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOTFOUND)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOWAIT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NULL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NUMBER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OF)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OFFLINE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ON)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ONLINE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OPTION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ORDER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PCTFREE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PRIOR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PRIVILEGES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PUBLIC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RAW)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RENAME)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RESOURCE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REVOKE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROW)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROWID)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROWLABEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROWNUM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROWS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SELECT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SESSION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SET)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SHARE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SIZE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SMALLINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQLBUF)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_START)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SUCCESSFUL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SYNONYM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SYSDATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TABLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_THEN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TO)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TINYINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MEDIUMINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TRIGGER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TRUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UID)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNIQUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UPDATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_USER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VALIDATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VALUES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VARCHAR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VARCHAR2)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VIEW)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_WHENEVER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_WHERE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_WITH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TEXT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TINYTEXT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MEDIUMTEXT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LONGTEXT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ENUM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SHOW)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_A)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ADMIN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AFTER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ALLOCATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ANALYZE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ARCHIVE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ARCHIVELOG)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AUTHORIZATION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AUTO_INCREMENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AVG)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BACKUP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BECOME)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BEFORE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BEGIN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BIGINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BLOCK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BODY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CACHE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CANCEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CASCADE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CHANGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CHARACTER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CHARSET)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CHECKPOINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CLOSE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COBOL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COLLATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COMMIT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COMPILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONSTRAINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONSTRAINTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONTENTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONTINUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONTROLFILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COLUMN_FORMAT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COUNT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CURSOR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CYCLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DATABASE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DATAFILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DAY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DBA)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DBTIMEZONE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DEC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DECLARE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DISABLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DISMOUNT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DOUBLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DUMP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DYNAMIC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EACH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ENABLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_END)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ENGINE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ESCAPE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EVENTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXCEPT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXCEPTIONS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXEC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXECUTE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXPLAIN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXTENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXTERNALLY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FETCH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FIXED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FLUSH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FORCE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FOREIGN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FORTRAN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FOUND)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FREELIST)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FREELISTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FUNCTION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_GO)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_GOTO)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_GROUPS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INCLUDING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INDICATOR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INITRANS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INSTANCE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_KEY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LANGUAGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LAYER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LINK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LISTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LOGFILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LOCAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LOCKED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MANAGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MANUAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAX)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXDATAFILES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXINSTANCES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXLOGFILES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXLOGHISTORY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXLOGMEMBERS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXTRANS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAXVALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MIN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MINEXTENTS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MINVALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MODULE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MONTH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MOUNT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NEW)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NEXT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOARCHIVELOG)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOCACHE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOCYCLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOMAXVALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOMINVALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NONE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOORDER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NORESETLOGS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NORMAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NOSORT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NUMERIC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OFF)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OLD)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ONLY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OPEN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OPTIMAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OWN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PACKAGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PARALLEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PCTINCREASE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PCTUSED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PLAN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PLI)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PRECISION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PRIMARY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PRIVATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PROCEDURE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PROFILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_QUOTA)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_READ)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RECOVER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REFERENCES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REFERENCING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RESETLOGS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RESTRICT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RESTRICTED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REUSE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROLES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROLLBACK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SAVEPOINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SCHEMA)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SCN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SECOND)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SECTION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SEGMENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SEQUENCE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SESSIONTIMEZONE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SHARED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SNAPSHOT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SKIP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SOME)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SORT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQLCODE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQLERROR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQLSTATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STATEMENT_ID)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STATISTICS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STOP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STORAGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SUM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SWITCH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SYSTEM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TABLES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TABLESPACE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TEMPORARY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_THREAD)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TIME)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TRACING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TRANSACTION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TRIGGERS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TRUNCATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNDER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNLIMITED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNTIL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_USE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_USING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_WAIT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_WHEN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_WORK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_WRITE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_YEAR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ZONE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_AUTOMATIC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BFILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BINARY_DOUBLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BINARY_FLOAT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BINARY_INTEGER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BLOB)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LONGBLOB)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MEDIUMBLOB)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TINYBLOB)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BOOLEAN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BYTE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CAST)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CLOB)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CLUSTER_SET)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COLUMN_VALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONNECT_BY_ISCYCLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONNECT_BY_ISLEAF)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CONNECT_BY_ROOT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CORR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COVAR_POP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_COVAR_SAMP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CROSS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CUBE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CUME_DIST)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DECREMENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DENSE_RANK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DIMENSION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EMPTY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EQUALS_PATH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FIRST_VALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FULL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_GROUPING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_IGNORE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INFINITE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INNER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INTERVAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ITERATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_JOIN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_KEEP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LAG)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LAST)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LAST_VALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LEAD)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LEFT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MAIN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MEASURES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MEMBER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MLSLABEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MODEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MULTISET)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NAN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NATIONAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NATURAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NAV)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NCHAR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NCLOB)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NTILE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NULLS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NVARCHAR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_NVARCHAR2)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OBJECT_ID)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OBJECT_VALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ORA_ROWSCN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OUTER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OVER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PARTITION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PERCENTILE_CONT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PERCENTILE_DISC)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PERCENT_RANK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PIVOT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PLS_INTEGER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_POSITIVE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PRESENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RANK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RATIO_TO_REPORT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REFERENCE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGEXP_LIKE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_AVGX)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_AVGY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_COUNT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_INTERCEPT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_R2)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_SLOPE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_SXX)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_SXY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REGR_SYY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RIGHT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROLLUP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ROW_NUMBER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RULES)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SAMPLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SEARCH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SEQUENTIAL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SETS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SINGLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STDDEV)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STDDEV_POP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STDDEV_SAMP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SUBMULTISET)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SUBPARTITION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_THE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TIMESTAMP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_TYPE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNBOUNDED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNDER_PATH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UPDATED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UPSERT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UROWID)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VARIANCE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VARYING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VAR_POP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VAR_SAMP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VERSIONS_ENDSCN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VERSIONS_ENDTIME)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VERSIONS_OPERATION)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VERSIONS_STARSCN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VERSIONS_STARTTIME)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VERSIONS_XID)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_XML)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_XMLDATA)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_ERRORS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FIRST)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LIMIT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_OFFSET)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LOG)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_REJECT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RETURN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RETURNING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MERGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MATCHED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FOLLOWING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RANGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SIBLINGS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNPIVOT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_UNSIGNED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_BREADTH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_DEPTH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_EXCLUDE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INCLUDE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MIVALUE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_PRECEDING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_RESPECT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SEED)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_VERSIONS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_HIGH_PRIORITY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_STRAIGHT_JOIN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQL_SMALL_RESULT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQL_BIG_RESULT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQL_BUFFER_RESULT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQL_CACHE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQL_NO_CACHE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_SQL_CALC_FOUND_ROWS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_INNODB)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_MYISAM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_LOW_PRIORITY)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_FULLTEXT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mK_CURRENT_TIMESTAMP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mSTUPID_MYSQL_DATE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mSTUPID_MYSQL_TIMESTAMP)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQUOTED_STRING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQSTRING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQS_ANGLE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQS_BRACE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQS_BRACK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQS_PAREN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQS_OTHER_CH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQS_OTHER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mID)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mSEMI)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mCOLON)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mDOUBLEDOT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mDOT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mPOINT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mCOMMA)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mEXPONENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mASTERISK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mAT_SIGN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mRPAREN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mLPAREN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mRBRACK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mLBRACK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mPLUS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mMINUS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mDIVIDE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mEQ)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mPERCENTAGE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mLLABEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mRLABEL)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mASSIGN)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mARROW)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mVERTBAR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mDOUBLEVERTBAR)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mNOT_EQ)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mLTH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mLEQ)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mGTH)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mGEQ)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mNUMBER)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mNUM)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mQUOTE)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mBACKTICK)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mDOUBLEQUOTED_STRING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mBACKQUOTED_STRING)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mWS)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mSL_COMMENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mML_COMMENT)	(struct mysqlLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct mysqlLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct mysqlLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pmysqlLexer mysqlLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pmysqlLexer mysqlLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define K_BINARY_FLOAT      148
#define K_FALSE      200
#define K_LAYER      452
#define K_MONTH      143
#define K_REFERENCING      494
#define K_REGEXP_LIKE      270
#define K_TRACING      519
#define K_PARTITION      228
#define K_CONNECT      241
#define K_ZONE      137
#define K_CREATE      30
#define K_RESOURCE      381
#define K_EXISTS      42
#define K_ARRAYLEN      359
#define K_ROW_NUMBER      328
#define K_CASCADE      68
#define K_GO      444
#define K_COLUMN      362
#define RPAREN      45
#define K_USE      28
#define K_STDDEV_SAMP      331
#define K_ROLE      498
#define K_LEFT      237
#define K_ADD      357
#define K_LOW_PRIORITY      26
#define K_ONLINE      376
#define K_VIEW      393
#define K_NOCOMPRESS      373
#define K_CLOB      186
#define GEQ      255
#define K_DATETIME      160
#define EQ      82
#define K_INCLUDE      355
#define K_RAW      157
#define K_PIVOT      351
#define K_NATURAL      150
#define K_RESTRICT      67
#define K_ORDER      289
#define DIVIDE      125
#define RBRACK      293
#define BACKQUOTED_STRING      121
#define K_UNDER_PATH      273
#define K_MAXLOGFILES      460
#define K_SESSIONTIMEZONE      139
#define K_OVER      337
#define K_SHARED      506
#define K_NOMAXVALUE      472
#define K_FREELISTS      442
#define K_NUMBER      152
#define K_IDENTIFIED      367
#define K_TEXT      167
#define K_ALLOCATE      397
#define K_MAXEXTENTS      370
#define K_FREELIST      441
#define K_DENSE_RANK      306
#define K_LONG      156
#define PERCENTAGE      538
#define K_NULLS      108
#define K_CLOSE      411
#define K_INDEX      59
#define QS_ANGLE      528
#define K_NOCYCLE      242
#define K_UNTIL      291
#define SL_COMMENT      546
#define K_SEQUENCE      505
#define K_CONSTRAINT      69
#define K_TIMESTAMP      162
#define K_NOWAIT      344
#define K_NOORDER      475
#define K_SQL      134
#define K_DESC      62
#define K_MEDIUMTEXT      169
#define K_MODULE      466
#define K_LEVEL      203
#define K_FULL      236
#define K_RESTRICTED      496
#define LBRACK      292
#define K_PERCENT_RANK      314
#define K_INITIAL      369
#define K_LOG      92
#define POINT      536
#define K_PRESENT      264
#define K_RANK      317
#define K_COLLATE      37
#define K_POSITIVE      151
#define K_VERSIONS_STARTTIME      206
#define K_TINYINT      195
#define K_DOUBLE      165
#define K_DECREMENT      295
#define K_PRECISION      166
#define K_LIMIT      95
#define K_REGR_COUNT      321
#define K_BOOLEAN      158
#define K_SEQUENTIAL      288
#define K_BLOB      185
#define K_EACH      426
#define K_TEMPORARY      38
#define K_BACKUP      402
#define K_TINYBLOB      182
#define K_INTO      78
#define K_NOSORT      478
#define K_CURRENT_TIMESTAMP      526
#define K_REVOKE      382
#define K_SECTION      503
#define K_VARCHAR      174
#define PLUS      122
#define K_SHOW      29
#define K_COMMIT      413
#define K_NATIONAL      179
#define K_UNLIMITED      96
#define K_NEXT      469
#define K_THEN      81
#define K_DEPTH      105
#define K_REFERENCE      280
#define K_DECIMAL      154
#define K_UNSIGNED      198
#define K_IS      250
#define K_WITH      103
#define K_CLUSTER_SET      144
#define K_IN      260
#define MINUS      123
#define K_SUBPARTITION      230
#define SEMI      19
#define T_CREATE_TABLE_ENUM      10
#define NOT_EQ      253
#define K_IF      40
#define VERTBAR      542
#define K_TINYTEXT      168
#define COLON      535
#define K_CURRENT      341
#define K_PRECEDING      339
#define K_MEDIUMINT      194
#define K_READ      24
#define T_CREATE_TABLE      6
#define K_CHECKPOINT      410
#define K_CONTINUE      417
#define K_MODIFY      371
#define K_PRIVATE      490
#define K_NCHAR      176
#define K_MEDIUMBLOB      183
#define ARROW      131
#define QS_OTHER_CH      534
#define K_MAXVALUE      223
#define K_NTILE      313
#define K_REAL      164
#define K_LIKE4      267
#define K_LIKE2      266
#define K_INT      192
#define T__569      569
#define K_PRIVILEGES      378
#define T__568      568
#define T__567      567
#define T__566      566
#define T__565      565
#define K_AUDIT      360
#define T__574      574
#define K_CONSTRAINTS      415
#define T__575      575
#define T__572      572
#define K_REJECT      94
#define T__573      573
#define K_SEARCH      104
#define K_MIVALUE      221
#define T__570      570
#define T__571      571
#define DOUBLEDOT      537
#define K_LIKEC      265
#define K_PUBLIC      379
#define K_LINK      453
#define K_PRIMARY      49
#define K_REFERENCES      65
#define T_SERVER_VARIABLE      15
#define QUOTE      533
#define K_LOCK      21
#define K_RECOVER      493
#define T__577      577
#define T__576      576
#define T__579      579
#define T__578      578
#define K_KEY      50
#define K_CHARACTER      33
#define T__583      583
#define K_UPSERT      286
#define T__580      580
#define T__581      581
#define T__582      582
#define K_TRUNCATE      522
#define K_UPDATED      281
#define K_ALL      88
#define K_QUOTA      492
#define K_OUTER      239
#define K_A      261
#define K_FIRST_VALUE      307
#define K_END      133
#define K_GROUPING      247
#define K_COUNT      304
#define K_VAR_SAMP      334
#define K_NORESETLOGS      476
#define K_GOTO      445
#define K_UPDATE      58
#define K_SUBMULTISET      271
#define K_PCTFREE      377
#define DOUBLEVERTBAR      124
#define K_INDICATOR      448
#define K_ONLY      76
#define K_VERSIONS_ENDSCN      209
#define K_NOMINVALUE      473
#define K_PROFILE      491
#define K_STRAIGHT_JOIN      113
#define K_ENGINE      71
#define T_SELECT_STATEMENT      17
#define BACKTICK      544
#define K_RIGHT      238
#define K_EXTERNALLY      435
#define K_CONTROLFILE      418
#define K_CONTENTS      416
#define K_WORK      524
#define K_ANY      258
#define K_STORAGE      56
#define K_MLSLABEL      180
#define K_AND      222
#define K_SHARE      348
#define K_RESETLOGS      495
#define K_GROUP      244
#define K_UID      390
#define K_SQLBUF      386
#define K_LIKE      43
#define K_PLI      489
#define K_STDDEV      329
#define K_SESSION      384
#define K_XMLDATA      216
#define K_NCLOB      187
#define K_INTERSECT      296
#define K_LOGFILE      455
#define K_VERSIONS_ENDTIME      208
#define K_DELETE      66
#define K_BY      107
#define K_PRIOR      126
#define ID      36
#define K_OFFLINE      375
#define K_MODEL      274
#define K_CORR      301
#define K_LEAD      310
#define K_SET      34
#define K_DATABASE      31
#define K_PCTINCREASE      486
#define COMMA      83
#define K_VARIANCE      335
#define K_BODY      406
#define K_OBJECT_ID      213
#define K_SETS      248
#define K_INCREMENT      294
#define K_WHENEVER      394
#define QUOTED_STRING      52
#define K_CUME_DIST      305
#define K_EXCEPT      429
#define K_SQLCODE      509
#define K_CYCLE      110
#define K_RETURNING      87
#define K_SQLSTATE      511
#define K_OFF      479
#define K_NORMAL      477
#define K_CHARSET      35
#define K_SQL_BIG_RESULT      115
#define K_THE      525
#define K_SAVEPOINT      501
#define K_PERCENTILE_CONT      315
#define K_VERSIONS_STARSCN      207
#define K_REGR_AVGY      324
#define K_EXCLUDE      354
#define K_REGR_AVGX      323
#define K_COVAR_POP      302
#define K_TABLESPACE      517
#define K_MIN      312
#define K_KEEP      276
#define K_HAVING      102
#define K_COMMENT      51
#define K_FORCE      438
#define K_DEFAULT      32
#define K_PACKAGE      484
#define K_SCN      220
#define K_BEFORE      404
#define K_NOTFOUND      374
#define K_SQL_SMALL_RESULT      114
#define K_DISMOUNT      424
#define K_COBOL      412
#define K_SIZE      385
#define K_OPTION      232
#define T_CREATE_TABLE_INDEX      7
#define ASSIGN      541
#define K_IGNORE      275
#define K_ROWNUM      202
#define T_USE_DATABASE      4
#define K_ROW      342
#define K_SEGMENT      504
#define K_SQL_NO_CACHE      118
#define K_AS      23
#define K_AT      135
#define QS_OTHER      532
#define STUPID_MYSQL_TIMESTAMP      130
#define K_RATIO_TO_REPORT      318
#define LEQ      257
#define K_INFINITE      252
#define K_MAXLOGHISTORY      461
#define K_EXCLUSIVE      364
#define K_OFFSET      299
#define K_VARCHAR2      175
#define K_BLOCK      226
#define K_PARALLEL      485
#define K_FUNCTION      443
#define K_RULES      285
#define K_DEC      155
#define K_MULTISET      146
#define EOF      -1
#define K_CONNECT_BY_ISLEAF      204
#define K_SORT      508
#define K_OBJECT_VALUE      214
#define K_DATE      159
#define K_DISTINCT      99
#define K_MINUS      297
#define K_DISTINCTROW      100
#define K_LAG      308
#define K_ANALYZE      398
#define K_ERRORS      93
#define K_TYPE      263
#define K_AFTER      396
#define K_FLUSH      437
#define K_ROLLUP      245
#define NUMBER      60
#define T_CREATE_TABLE_OPTIONS      8
#define AT_SIGN      91
#define K_EXECUTE      432
#define K_FIXED      54
#define K_VARYING      172
#define K_TRANSACTION      520
#define K_PLAN      488
#define K_SQLERROR      510
#define K_NEW      468
#define K_RETURN      86
#define K_MINEXTENTS      464
#define K_SMALLINT      196
#define WS      545
#define K_LOCAL      25
#define K_CONNECT_BY_ISCYCLE      205
#define K_NOT      41
#define T_CREATE_TABLE_FULLTEXT_INDEX      11
#define K_DBA      421
#define K_BINARY_INTEGER      147
#define K_VERSIONS      218
#define K_ESCAPE      268
#define K_DAY      140
#define K_LONGBLOB      184
#define K_ROWS      282
#define K_LAST      109
#define K_CHAR      171
#define K_JOIN      234
#define K_STATEMENT_ID      512
#define K_FOLLOWING      340
#define K_FOUND      440
#define STUPID_MYSQL_DATE      129
#define K_OLD      480
#define K_UNIQUE      48
#define K_FOR      229
#define K_UNION      101
#define LLABEL      539
#define K_EQUALS_PATH      272
#define K_MATCHED      80
#define ASTERISK      120
#define LPAREN      44
#define K_ENUM      191
#define K_THREAD      518
#define RLABEL      540
#define K_GROUPS      446
#define K_INSTANCE      450
#define K_HIGH_PRIORITY      112
#define K_START      243
#define K_CUBE      246
#define K_SYSDATE      201
#define K_ROWLABEL      383
#define K_ADMIN      395
#define K_REGR_SXY      327
#define K_REGR_SXX      325
#define K_REGR_SLOPE      319
#define K_TABLE      39
#define QSTRING      527
#define K_UNBOUNDED      338
#define K_MERGE      77
#define K_FIRST      89
#define K_SAMPLE      225
#define K_BEGIN      405
#define K_UNPIVOT      353
#define T_SHOW_DATABASES      5
#define K_SKIP      346
#define K_MAX      311
#define K_DBTIMEZONE      138
#define K_ROLLBACK      500
#define K_SCHEMA      502
#define T__564      564
#define K_WAIT      345
#define T__563      563
#define T__562      562
#define T__561      561
#define K_OPTIMAL      482
#define T__560      560
#define K_ENABLE      427
#define T__558      558
#define T__559      559
#define K_BREADTH      106
#define T__556      556
#define T__557      557
#define K_NAV      277
#define T__554      554
#define K_SQL_CALC_FOUND_ROWS      119
#define K_REGR_SYY      326
#define T__555      555
#define K_INNER      233
#define K_LONGTEXT      170
#define K_ELSE      90
#define K_FORTRAN      439
#define K_YEAR      142
#define K_NAN      251
#define K_DISABLE      423
#define K_FROM      75
#define K_BETWEEN      219
#define T_LOCK_TABLE      16
#define K_MYISAM      72
#define T__551      551
#define T__550      550
#define T__553      553
#define T__552      552
#define T__548      548
#define T__549      549
#define K_MANUAL      457
#define K_NONE      474
#define K_ITERATE      290
#define K_FULLTEXT      63
#define K_PERCENTILE_DISC      316
#define K_WHEN      79
#define K_INITRANS      449
#define K_FOREIGN      64
#define K_XML      352
#define K_USER      391
#define K_EXPLAIN      433
#define K_VERSIONS_XID      210
#define K_WRITE      27
#define K_SYNONYM      388
#define QS_PAREN      531
#define EXPONENT      128
#define K_CHANGE      409
#define K_INCLUDING      447
#define K_TRUE      199
#define K_FETCH      436
#define K_MINVALUE      465
#define K_STATISTICS      513
#define K_PCTUSED      487
#define K_LANGUAGE      451
#define K_MAXLOGMEMBERS      462
#define K_MOUNT      467
#define K_OR      249
#define K_ORA_ROWSCN      215
#define K_VALUES      85
#define K_GRANT      366
#define K_ON      57
#define K_CONNECT_BY_ROOT      127
#define K_USING      70
#define K_ASC      61
#define K_VALUE      97
#define K_EMPTY      262
#define K_CLUSTER      361
#define K_AUTHORIZATION      401
#define K_MEMBER      269
#define K_UROWID      190
#define T_CREATE_TABLE_ONUPDATE      12
#define K_MAXDATAFILES      458
#define K_MAIN      283
#define T_TRANSFORM      18
#define K_CANCEL      408
#define K_ACCESS      356
#define K_STOP      514
#define K_OF      224
#define K_NUMERIC      153
#define QS_BRACE      529
#define K_FILE      365
#define K_LISTS      454
#define K_INNODB      73
#define QS_BRACK      530
#define K_ROWID      189
#define K_MANAGE      456
#define K_AUTO_INCREMENT      47
#define K_MODE      349
#define K_TRIGGERS      521
#define K_STDDEV_POP      330
#define K_REGR_R2      322
#define K_DYNAMIC      55
#define K_EXTENT      434
#define K_IMMEDIATE      368
#define K_MEASURES      284
#define K_INSERT      84
#define K_ROLES      499
#define K_MAXINSTANCES      459
#define K_RENAME      380
#define K_NVARCHAR      177
#define K_AUTOMATIC      287
#define K_NOAUDIT      372
#define K_COLUMN_VALUE      212
#define K_VERSIONS_OPERATION      211
#define K_SOME      259
#define K_NULL      46
#define K_COVAR_SAMP      303
#define K_SQL_CACHE      117
#define K_SQL_BUFFER_RESULT      116
#define K_OPEN      481
#define K_EVENTS      428
#define K_ARCHIVELOG      400
#define K_UNDER      523
#define K_CACHE      407
#define K_TABLES      20
#define K_COMPILE      414
#define K_BYTE      173
#define K_COMPRESS      363
#define K_SUM      332
#define GTH      254
#define K_SIBLINGS      298
#define K_COLUMN_FORMAT      53
#define K_TO      111
#define K_NOCACHE      471
#define K_FLOAT      163
#define K_BINARY_DOUBLE      149
#define K_EXEC      431
#define K_SELECT      98
#define K_CURSOR      419
#define K_ALTER      358
#define K_TRIGGER      389
#define K_WHERE      240
#define K_RESPECT      336
#define ML_COMMENT      547
#define K_LAST_VALUE      309
#define K_BFILE      188
#define K_SEED      227
#define K_PLS_INTEGER      181
#define K_CASE      132
#define K_DIMENSION      278
#define K_PROCEDURE      350
#define K_VAR_POP      333
#define K_EXCEPTIONS      430
#define K_SYSTEM      516
#define K_SWITCH      515
#define K_CROSS      235
#define DOT      22
#define K_CAST      145
#define K_CHECK      231
#define K_RANGE      343
#define K_DECLARE      422
#define K_MAXTRANS      463
#define K_AVG      300
#define K_INTERVAL      161
#define K_LOCKED      347
#define K_BECOME      403
#define K_NOARCHIVELOG      470
#define K_NVARCHAR2      178
#define T_CREATE_TABLE_FKEY      9
#define T_CREATE_TABLE_COLUMN_DEFAULT      13
#define K_INTEGER      193
#define DOUBLEQUOTED_STRING      217
#define NUM      543
#define K_ARCHIVE      399
#define LTH      256
#define K_SUCCESSFUL      387
#define K_SNAPSHOT      507
#define K_DATAFILE      420
#define T_CREATE_TABLE_COLUMN_DEF      14
#define K_DUMP      425
#define K_REUSE      497
#define K_VALIDATE      392
#define K_REGR_INTERCEPT      320
#define K_DROP      74
#define K_TIME      136
#define K_SECOND      141
#define K_BIGINT      197
#define K_SINGLE      279
#define K_OWN      483
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for mysqlLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
